export enum AccountType {
    CURVECUBE = 'CURVECUBE',
    PAGON = 'PAGON',
    DEALER = 'DEALER',
    VTS_DEALER = 'VTS_DEALER',
    SBT_DEALER = 'SBT_DEALER',
    TRANSPORT_COMPANY = 'TRANSPORT_COMPANY',
    SCHOOL_GROUP = 'SCHOOL_GROUP',
    SCHOOL_BRANCH = 'SCHOOL_BRANCH',
    SCHOOL = 'SCHOOL'
}
